setwd("H:/")
mydata<-read.table(file = "Украина.txt", header = TRUE)
attach(mydata)
plot(Year, terrorism, xlab = "Год", ylab = "Частота", main="Частота упоминаний характеристик для Грузии", pch=15, col="red", type="b", xlim=c(2000,2014), ylim=c(0,max(mydata)))
lines (Year,terrorist, xlim=c(2000,2014), pch=14, col="green", type="b")
lines (Year,occupation, xlim=c(2000,2014), pch=16, col="blacK", type="b")
lines (Year,narcotic, xlim=c(2000,2014), pch=17, col="yellow", type="b")
lines (Year,violation, xlim=c(2000,2014), pch=18, col="orange", type="b")
lines (Year,democracy, xlim=c(2000,2014), pch=19, col="blue", type="b")
lines (Year,development, xlim=c(2000,2014), pch=20, col="brown", type="b")
legend ("topleft", inset=0.01, title="Характеристики", c("терроризм", "террорист", "оккупация", "наркотики", "насилие", "демократия", "развитие"), lty=c(1,1,1,1,1,1,1), pch=c(15,14,16,17,18,19,20), col=c("red","green","black","yellow", "orange", "blue", "brown"))
